apiVersion: v1
kind: Service
metadata:
  name: hugo-nginx-svc
  labels:
    run: hugo-nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    run: hugo-nginx
