apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hugo-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: hugo-app
    spec:
      securityContext:
        fsGroup: 99
      containers:
        - name: hugo-app
          image: smesch/hugo-app:1
          ports:
            - containerPort: 80
